apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ladybugdb-pvc
  namespace: ladybugdb
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  volumeName: ladybugdb-pv
  resources:
    requests:
      storage: 10Gi
